apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration

address: '0.0.0.0'
maxPods: _MAX_PODS_

authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: true
  x509:
    clientCAFile: '/etc/kubernetes/pki/ca.crt'

authorization:
  mode: Webhook

clusterDomain: 'cluster.local'
clusterDNS:
  - 172.20.0.10
  - 172.20.0.20
cgroupDriver: 'cgroupfs'

enforceNodeAllocatable: [pods]
kubeReserved:
  cpu: "1000m"
  memory: "2Gi"
systemReserved:
  cpu: "500m"
  memory: "1Gi"

evictionHard:
  memory.available: "100Mi"
  nodefs.available: "5%"
evictionSoft:
  memory.available: "300Mi"
  nodefs.available: "10%"
evictionSoftGracePeriod:
  memory.available: "60s"
  nodefs.available: "60s"

failSwapOn: true

featureGates:
  RotateKubeletServerCertificate: true
